# Generated by Django 2.0.3 on 2018-04-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAccounts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mail_id', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(verbose_name='date published')),
                ('account_id', models.CharField(max_length=200)),
                ('account_password', models.CharField(max_length=200)),
                ('account_balance', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('txn_id', models.AutoField(primary_key=True, serialize=False)),
                ('txn_hash', models.CharField(max_length=200)),
                ('txn_from_address', models.CharField(max_length=200)),
                ('txn_value', models.CharField(max_length=200)),
            ],
        ),
    ]
