# Generated by Django 2.0.3 on 2018-04-06 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeraccounts',
            old_name='mail_id',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='customeraccounts',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='customeraccounts',
            name='password',
        ),
    ]
