# Generated by Django 2.0.3 on 2018-04-06 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20180406_1600'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
